openapi: 3.0.0
info:
  title: Contact API Contract
  version: 1.0.0
  description: |
    飞书通讯录 API 契约定义
    包含用户查询、部门查询、群组查询、缓存管理等功能

servers:
  - url: https://open.feishu.cn/open-apis
    description: 飞书开放平台

components:
  schemas:
    # ==================== User 相关 ====================
    User:
      type: object
      required:
        - open_id
        - user_id
        - union_id
        - name
        - status
      properties:
        open_id:
          type: string
          pattern: '^ou_[a-zA-Z0-9]{16}$'
          description: 应用内用户标识
          example: ou_abc123def456ghi7
        user_id:
          type: string
          description: 租户内用户标识
          example: '7g9j1234'
        union_id:
          type: string
          pattern: '^on_[a-zA-Z0-9]{16}$'
          description: 跨租户用户标识
          example: on_xyz789abc123def4
        name:
          type: string
          minLength: 1
          maxLength: 100
          description: 用户姓名
        en_name:
          type: string
          maxLength: 100
          description: 英文名
          nullable: true
        email:
          type: string
          format: email
          description: 邮箱
          nullable: true
        mobile:
          type: string
          pattern: '^\+?[1-9]\d{1,14}$'
          description: 手机号 (E.164 格式)
          nullable: true
        avatar:
          type: string
          format: uri
          description: 头像 URL
          nullable: true
        department_ids:
          type: array
          items:
            type: string
          description: 所属部门 ID 列表
          default: []
        status:
          type: integer
          enum: [1, 2, 4, 5]
          description: |
            用户状态:
            1 - 正常
            2 - 停用
            4 - 未激活
            5 - 退出企业
        employee_type:
          type: integer
          enum: [1, 2, 3, 4, 5]
          description: |
            员工类型:
            1 - 正式员工
            2 - 实习生
            3 - 外包
            4 - 劳务
            5 - 顾问
        join_time:
          type: integer
          format: int64
          description: 入职时间 (Unix timestamp)
          nullable: true

    UserCache:
      type: object
      required:
        - app_id
        - union_id
        - open_id
        - user_id
        - name
        - cached_at
      properties:
        app_id:
          type: string
          pattern: '^cli_[a-z0-9]{16}$'
          description: 应用 ID
        union_id:
          type: string
          pattern: '^on_[a-zA-Z0-9]{16}$'
          description: 跨租户用户标识
        open_id:
          type: string
          pattern: '^ou_[a-zA-Z0-9]{16}$'
          description: 应用内用户标识
        user_id:
          type: string
          description: 租户内用户标识
        name:
          type: string
          description: 用户姓名
        email:
          type: string
          format: email
          nullable: true
        mobile:
          type: string
          nullable: true
        avatar:
          type: string
          format: uri
          nullable: true
        department_ids:
          type: array
          items:
            type: string
          default: []
        cached_at:
          type: string
          format: date-time
          description: 缓存时间
        ttl:
          type: integer
          default: 86400
          description: 缓存有效期 (秒)
        version:
          type: integer
          default: 1
          description: 缓存版本号 (用于乐观锁)

    # ==================== Department 相关 ====================
    Department:
      type: object
      required:
        - department_id
        - name
        - parent_department_id
      properties:
        department_id:
          type: string
          pattern: '^dept_[a-zA-Z0-9]{16}$'
          description: 部门 ID
          example: dept_abc123def456ghi7
        name:
          type: string
          minLength: 1
          maxLength: 100
          description: 部门名称
        parent_department_id:
          type: string
          description: 父部门 ID
        leader_user_id:
          type: string
          description: 部门负责人 user_id
          nullable: true
        member_count:
          type: integer
          minimum: 0
          description: 部门成员数
        status:
          type: integer
          enum: [1, 2]
          description: |
            部门状态:
            1 - 正常
            2 - 停用
        order:
          type: integer
          description: 部门排序

    # ==================== ChatGroup 相关 ====================
    ChatGroup:
      type: object
      required:
        - chat_id
        - name
        - owner_id
      properties:
        chat_id:
          type: string
          pattern: '^oc_[a-zA-Z0-9]{16}$'
          description: 群组 ID
          example: oc_abc123def456ghi7
        name:
          type: string
          minLength: 1
          maxLength: 100
          description: 群组名称
        description:
          type: string
          maxLength: 500
          description: 群组描述
          nullable: true
        owner_id:
          type: string
          description: 群主 open_id
        avatar:
          type: string
          format: uri
          description: 群头像 URL
          nullable: true
        member_count:
          type: integer
          minimum: 0
          description: 群成员数
        chat_type:
          type: string
          enum: [private, public]
          description: 群类型
        created_at:
          type: string
          format: date-time
          description: 创建时间

    # ==================== Error 相关 ====================
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          description: |
            错误码:
            40101 - 用户不存在
            40102 - 邮箱格式错误
            40103 - 部门不存在
            40104 - 群组不存在
            40105 - 权限不足
            50101 - 缓存写入失败
            50102 - API 调用超时
        message:
          type: string
          description: 错误消息
        details:
          type: object
          description: 错误详情
          properties:
            field:
              type: string
              description: 错误字段
            suggestion:
              type: string
              description: 修复建议
        request_id:
          type: string
          description: 请求 ID

paths:
  # ==================== 用户查询 ====================
  /contact/v3/users/{user_id}:
    get:
      summary: 根据 user_id 查询用户
      operationId: getUserById
      tags:
        - User
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
        - name: user_id_type
          in: query
          schema:
            type: string
            enum: [open_id, user_id, union_id]
            default: open_id
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 0
                  msg:
                    type: string
                    example: success
                  data:
                    type: object
                    properties:
                      user:
                        $ref: '#/components/schemas/User'
        '404':
          description: 用户不存在
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /contact/v3/users/batch_get_id:
    post:
      summary: 通过邮箱或手机号批量查询用户
      operationId: getUsersByEmailOrMobile
      tags:
        - User
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                emails:
                  type: array
                  items:
                    type: string
                    format: email
                  maxItems: 200
                  description: 邮箱列表
                mobiles:
                  type: array
                  items:
                    type: string
                  maxItems: 200
                  description: 手机号列表
                user_id_type:
                  type: string
                  enum: [open_id, user_id, union_id]
                  default: open_id
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  msg:
                    type: string
                  data:
                    type: object
                    properties:
                      user_list:
                        type: array
                        items:
                          $ref: '#/components/schemas/User'

  # ==================== 部门查询 ====================
  /contact/v3/departments/{department_id}:
    get:
      summary: 查询部门信息
      operationId: getDepartment
      tags:
        - Department
      parameters:
        - name: department_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  msg:
                    type: string
                  data:
                    type: object
                    properties:
                      department:
                        $ref: '#/components/schemas/Department'

  /contact/v3/departments/{department_id}/children:
    get:
      summary: 获取子部门列表
      operationId: getChildDepartments
      tags:
        - Department
      parameters:
        - name: department_id
          in: path
          required: true
          schema:
            type: string
        - name: page_size
          in: query
          schema:
            type: integer
            minimum: 1
            maximum: 50
            default: 20
        - name: page_token
          in: query
          schema:
            type: string
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  msg:
                    type: string
                  data:
                    type: object
                    properties:
                      items:
                        type: array
                        items:
                          $ref: '#/components/schemas/Department'
                      has_more:
                        type: boolean
                      page_token:
                        type: string

  /contact/v3/users:
    get:
      summary: 获取部门用户列表
      operationId: getDepartmentUsers
      tags:
        - Department
      parameters:
        - name: department_id
          in: query
          required: true
          schema:
            type: string
        - name: page_size
          in: query
          schema:
            type: integer
            minimum: 1
            maximum: 50
            default: 20
        - name: page_token
          in: query
          schema:
            type: string
        - name: user_id_type
          in: query
          schema:
            type: string
            enum: [open_id, user_id, union_id]
            default: open_id
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  msg:
                    type: string
                  data:
                    type: object
                    properties:
                      items:
                        type: array
                        items:
                          $ref: '#/components/schemas/User'
                      has_more:
                        type: boolean
                      page_token:
                        type: string

  # ==================== 群组查询 ====================
  /im/v1/chats/{chat_id}:
    get:
      summary: 查询群组信息
      operationId: getChat
      tags:
        - Chat
      parameters:
        - name: chat_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  msg:
                    type: string
                  data:
                    type: object
                    properties:
                      chat:
                        $ref: '#/components/schemas/ChatGroup'

  /im/v1/chats:
    get:
      summary: 查询群组列表
      operationId: listChats
      tags:
        - Chat
      parameters:
        - name: page_size
          in: query
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
        - name: page_token
          in: query
          schema:
            type: string
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  msg:
                    type: string
                  data:
                    type: object
                    properties:
                      items:
                        type: array
                        items:
                          $ref: '#/components/schemas/ChatGroup'
                      has_more:
                        type: boolean
                      page_token:
                        type: string

  /im/v1/chats/{chat_id}/members:
    get:
      summary: 获取群成员列表
      operationId: getChatMembers
      tags:
        - Chat
      parameters:
        - name: chat_id
          in: path
          required: true
          schema:
            type: string
        - name: page_size
          in: query
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
        - name: page_token
          in: query
          schema:
            type: string
        - name: member_id_type
          in: query
          schema:
            type: string
            enum: [open_id, user_id, union_id]
            default: open_id
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                  msg:
                    type: string
                  data:
                    type: object
                    properties:
                      items:
                        type: array
                        items:
                          type: object
                          properties:
                            member_id:
                              type: string
                            name:
                              type: string
                            tenant_key:
                              type: string
                      has_more:
                        type: boolean
                      page_token:
                        type: string

  # ==================== 缓存管理 (内部 API) ====================
  /internal/cache/users/{union_id}:
    get:
      summary: 获取用户缓存
      operationId: getUserCache
      tags:
        - Cache
      parameters:
        - name: union_id
          in: path
          required: true
          schema:
            type: string
        - name: app_id
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserCache'
        '404':
          description: 缓存未命中

    put:
      summary: 更新用户缓存
      operationId: updateUserCache
      tags:
        - Cache
      parameters:
        - name: union_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCache'
      responses:
        '200':
          description: 成功
        '409':
          description: 版本冲突
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    delete:
      summary: 清除用户缓存
      operationId: deleteUserCache
      tags:
        - Cache
      parameters:
        - name: union_id
          in: path
          required: true
          schema:
            type: string
        - name: app_id
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 成功

  /internal/cache/users:
    delete:
      summary: 批量清除用户缓存
      operationId: batchDeleteUserCache
      tags:
        - Cache
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - union_ids
                - app_id
              properties:
                union_ids:
                  type: array
                  items:
                    type: string
                  maxItems: 1000
                app_id:
                  type: string
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  deleted_count:
                    type: integer
